#include "ColumnTreeViewColors.h"

typedef column_tree_item_colors	column_list_item_colors;
typedef column_tree_view_colors	column_tree_view_colors;

#define kDefaultColumnListItemColors	kDefaultColumnTreeItemColors
#define kDefaultColumnListViewColors	kDefaultColumnTreeViewColors
