#ifndef ERRORS_H
#define ERRORS_H


#include <errno.h>


#define B_OK	0

#if ENOMEM > 0
#	define _WONDERBRUSH_TO_NEGATIVE_ERROR(error)	(-(error))
#	define _WONDERBRUSH_TO_NATIVE_ERROR(error)		(-(error))
#else
#	define _WONDERBRUSH_TO_NEGATIVE_ERROR(error)	(error)
#	define _WONDERBRUSH_TO_NATIVE_ERROR(error)		(error)
#endif

#define B_NO_MEMORY			_WONDERBRUSH_TO_NEGATIVE_ERROR(ENOMEM)
#define B_BAD_VALUE			_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_TIMED_OUT			_WONDERBRUSH_TO_NEGATIVE_ERROR(ETIMEDOUT)
#define B_WOULD_BLOCK		_WONDERBRUSH_TO_NEGATIVE_ERROR(EWOULDBLOCK)
#define B_NOT_ALLOWED		_WONDERBRUSH_TO_NEGATIVE_ERROR(EPERM)
#define B_ENTRY_NOT_FOUND	_WONDERBRUSH_TO_NEGATIVE_ERROR(ENOENT)
#define B_INTERRUPTED		_WONDERBRUSH_TO_NEGATIVE_ERROR(EINTR)
#define B_BUSY				_WONDERBRUSH_TO_NEGATIVE_ERROR(EBUSY)
#define B_PERMISSION_DENIED	_WONDERBRUSH_TO_NEGATIVE_ERROR(EACCES)


// TODO: Find better mappings for the following error codes.
#define B_ERROR				_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_NO_INIT			_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_NAME_NOT_FOUND	_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_SEM_ID		_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_THREAD_ID		_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_NOT_A_MESSAGE		_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_DATA			_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_TYPE			_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_INDEX			_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BUFFER_OVERFLOW	_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_SCRIPT_SYNTAX	_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_MISMATCHED_VALUES	_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)
#define B_BAD_HANDLER		_WONDERBRUSH_TO_NEGATIVE_ERROR(EINVAL)


#endif // ERRORS_H
